# Generated by Django 5.2.11 on 2026-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_mindmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='content',
            field=models.JSONField(),
        ),
    ]
