# Generated by Django 5.2.12 on 2026-03-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_mindmap_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.studydocument'),
        ),
    ]
