# Generated by Django 5.2.11 on 2026-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_quizattempt_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
