# Generated by Django 5.2.12 on 2026-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_revisionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='map_type',
            field=models.CharField(default='overview', max_length=50),
        ),
    ]
